### ISSUE TITLE
LUA error on hunter player

### ISSUE THREAD

**Issue by Aethersailor** [Oppzippy/TankMD#20] opened 2024-08-27 16:34 UTC
Message: bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))
Time: Tue Aug 27 23:33:00 2024
Count: 1
Stack: bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))
[string "@Interface/AddOns/TankMD/Libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua"]:345: in function `GetCachedTalentInfoByID'
[string "@Interface/AddOns/TankMD/Libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua"]:599: in function `BuildInfo'
[string "@Interface/AddOns/TankMD/Libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua"]:281: in function `eventhandler'
[string "@Interface/AddOns/TankMD/Libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua"]:131: in function <...kMD/Libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:129>

Locals: self = <table> {
hooked = true
state = <table> {
}
cache = <table> {
}
static_cache = <table> {
}
events = <table> {
}
frame = LibGroupInSpecT-1.1_Frame {
}
}
talent_id = 123375
config_id = 1301
talents = <table> {
}
talent = nil
entry = <table> {
subTreeID = 53
type = 2
conditionIDs = <table> {
}
entryCost = <table> {
}
isDisplayError = false
isAvailable = true
maxRanks = 1
}
C_Traits = <table> {
}

**Comment by Oppzippy** [comment] 2024-08-27 21:23
Thanks for reporting, I'll fix later today. Closing since it's a duplicate of #19.

**Closed by Oppzippy** 2024-08-27 21:23 UTC
